style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/uazo/cromite
options:
  commits:
    filters:
      Type:
        - "[AUTO]"
  commit_groups:
    # title_maps: []
  header:
    pattern: "^(\\[.*\\])?(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
